<a href="https://colab.research.google.com/github/peeyush91099/minor_project/blob/main/Minor_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%ls '/content/drive/MyDrive/images'

Female/  Male/


In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from skimage.transform import resize
from skimage.io import imread


In [8]:
target = [] 
images = [] # Matrix Format
flat_data = [] 

DATADIR = '/content/drive/MyDrive/images'

CATEGORIES = ['Female','Male']

for i in CATEGORIES:
  class_target = CATEGORIES.index(i) # Label Encoded the Target value
  path = os.path.join(DATADIR,i)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized = resize(img_array,(150,150,3)) # Skimage normalizes the value
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_target)
    

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)
flat_data

array([[0.85098039, 0.86666667, 0.87058824, ..., 1.        , 1.        ,
        1.        ],
       [0.99607843, 0.92941176, 0.62352941, ..., 0.85533333, 0.67494118,
        0.58082353],
       [0.83137255, 0.83137255, 0.83137255, ..., 0.65882353, 0.65882353,
        0.65882353],
       ...,
       [0.91372549, 0.90588235, 0.90980392, ..., 0.87843137, 0.87843137,
        0.87679739],
       [0.94117647, 0.94509804, 0.95294118, ..., 0.67101961, 0.67886275,
        0.6592549 ],
       [0.78966013, 0.82745098, 0.85240523, ..., 0.90980392, 0.91822222,
        0.93783007]])

In [6]:
df = pd.DataFrame(flat_data)
df['Target'] = target
df

0         1         2  ...     67498     67499  Target
0   0.850980  0.866667  0.870588  ...  1.000000  1.000000       0
1   0.996078  0.929412  0.623529  ...  0.674941  0.580824       0
2   0.831373  0.831373  0.831373  ...  0.658824  0.658824       0
3   0.850980  0.906993  0.933333  ...  0.796405  0.855817       0
4   0.868869  0.794359  0.739458  ...  0.169046  0.148242       0
..       ...       ...       ...  ...       ...       ...     ...
67  0.996078  0.992157  0.976471  ...  0.299065  0.295144       1
68  0.015830  0.079958  0.011356  ...  0.068703  0.041252       1
69  0.913725  0.905882  0.909804  ...  0.878431  0.876797       1
70  0.941176  0.945098  0.952941  ...  0.678863  0.659255       1
71  0.789660  0.827451  0.852405  ...  0.918222  0.937830       1

[72 rows x 67501 columns]

In [95]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data,target,test_size = 0.25,random_state=109,stratify=target)
print(x_train.shape)
print(x_test.shape)

(54, 67500)
(18, 67500)


In [31]:
np.unique(y_train,return_counts=True)

(array([0, 1]), array([27, 27]))

In [13]:
np.unique(y_test,return_counts=True)

(array([0, 1]), array([9, 9]))

In [100]:
from sklearn.model_selection import GridSearchCV
svc = SVC(probability=True)
parameters = {
    'kernel':['linear','rbf'],
    'C':[0.1,1,10,100]
}
cv = GridSearchCV(svc,parameters,cv =5)
cv.fit(x_train,y_train)
cv.best_params_

{'C': 10, 'kernel': 'rbf'}

In [101]:
y_pred = cv.predict(x_test)
y_pred

array([1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1])

In [102]:
y_test

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1])

In [69]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


In [103]:
accuracy_score(y_pred,y_test)

0.7777777777777778